README.rst

I struggle a good 15 minutes trying to understand why Kalamine does not work on Windows. Of course this is due to encoding defaults of the cursed OS.
This may help some users I guess :)
Edit: this is an issue from the yaml library that can't open the data files (like `dead_keys.yaml`)

Add a note on windows encoding issue

---

README.rst
kalamine/cli.py

Following the discussion in #29, @nivopol has pointed me to a quick and straight-forward way to install a keyboard layout on XKB without running kalamine as root:
https://who-t.blogspot.com/2021/02/a-pre-supplied-custom-keyboard-layout.html
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/189/diffs
Here’s an attempt. It seems to work for me on Xorg (i3) and Wayland (sway): kalamine now produces an `*.xkb_patch` file, which can be sudo-copied to `/usr/share/X11/xkb/symbols/custom`.
It still requires `sudo` but it’s a valuable improvement. One of the cool benefits is that (if supported) this `symbols/custom` file will not be overwritten if the OS updates XKB.

new `xkb/symbols/custom` target

---

README.rst
layouts/ansi.toml
layouts/intl.toml

I wrote a """small""" install root/Arch install guide. I tried to be concise, but I still added about 50 lines (including empty lines) to the file, so if it’s a bit long for you I can try and make it a bit more compact.
I also added the missing `variant` field in some of the layouts, using the same naming convention you used in `prog.toml`

Root install guide

---

kalamine/xkb_manager.py

`dedent` is from the `textwrap` module and failed to create the `.config/xkb` on archlinux.
This seems to fix it (the module seems to be native and don't require changes in `pyproject.toml`).

Missing dedent dependency

---

kalamine/template.py

Partial fix for #55. Suits current Ergo-L needs but full support for dead keys in the `1dk` layer still needs more work.

[keylayout] support for double 1dk press

---

kalamine/data/dead_keys.yaml
kalamine/layout.py
kalamine/template.py
kalamine/tpl/base.xkb
kalamine/tpl/full_1dk.xkb_patch

Until now, kalamine used to generate XKB layouts where the AltGr key was an `ISO_Level5_Shift`, and the `1dk` was an `ISO_Level3_Latch`. This is unnatural and possibly confusing, e.g. :
- Gnome Tweaks sets the AltGr key to a Level3 shift by default
- the Compose key seems to always work with Level3 symbols, but not always with Level5
The reason for this was that I had never been able to make an `ISO_Level5_Latch` work… until now. And it’s so simple that I really can’t figure out how I could’ve missed that.
Anyway. Here’s a quick patch to test it. Let’s find out if it breaks [on older systems](https://lists.x.org/archives/xorg-devel/2011-August/024223.html).

[xkb] AltGr = Level3_Shift, 1dk = Level5_Latch

---

kalamine/template.py

Fixes #62… sort of. We still need to generate proper codes for these keys in order to support ABNT and JIS keyboards.

[klc] ignore ABNT and JIS keys (unsupported)

---

.gitignore
Makefile
kalamine/cli.py
kalamine/layout.py
kalamine/template.py
kalamine/tpl/x-keyboard.svg
kalamine/xkb_manager.py
pyproject.toml

This MR adds SVG rending as a new file output. This is generated as any other file type.
To test it, simply run (e.g. for `ergol.toml` file)
```
python -m kalamine.cli --out ergol.svg layouts/ergol.toml
```
To test all rending classes, add `dk`, `altgr`, `mixed` classes to main `svg` tag to display resp. 1st deadkey, altgr and a mixed view layer.

Enable SVG output

---

kalamine/xkb_manager.py

Old versions of lxml (before 4.8.0) cannot take a pathlib.Path object in etree.parse. One could fix a minimal version for lxml but the issue happens only twice and can be fixed by adding five characters.
Fixes #77

Make sure etree.parse gets a string

---

kalamine/layout.py
kalamine/template.py
kalamine/utils.py

Assorted type annotations fixes. In order to work reliably, type annotations need to get rid of all the "dictionary bags". So this PR also introduces more structured data types for `DEAD_KEYS` and `GEOMETRY`. It also reduces the number of abuse of the fact that `Layer` objects are secretly `int`.
Note: I tried to produce reviewable individual commits, but this required some history rewriting because I was not rigorous enough when editing. It should be mostly ok except for a couple of phantom line deletions that should be ignored in early commits.

Type fixes

---

kalamine/cli.py
kalamine/cli_xkb.py
kalamine/layout.py
kalamine/server.py
kalamine/template.py
kalamine/utils.py
kalamine/xkb_manager.py

This is built on top of #84. There is no point reviewing this before #84. 
With this PR, mypy no longer complains, even with options `--disallow-subclassing-any --disallow-untyped-defs`.

More type fixes

---

kalamine/cli.py
kalamine/layout.py
kalamine/tpl/x-keyboard.svg
tests/util.py

Improving svg classical deadkeys: removing `*` prefix and setting they in red.
Adding a `base` class on css to dispaly Alpha keys and deadkey layer.

SVG view improvements 

---

kalamine/tpl/base.ahk
kalamine/tpl/full.ahk

It works when an obvious upper case is found, so it will not work for the num row  and other symbols

fix(ahk): support for capslock key

---

README.rst
kalamine/server.py
pyproject.toml

Fixes an old regression caused by the switch from `os.path` to `pathlib` here: https://github.com/OneDeadKey/kalamine/commit/3da728f63a9d1b2bcd37919de1076146b25da0b3
And fixes a very recent regression caused by the switch from `pathlib` to `pkgutil` in #99.

bugfix: `kalamine watch`

---

.github/workflows/tests.yml
Makefile
docs/xkb.md
kalamine/cli.py
kalamine/cli_xkb.py
kalamine/layout.py
kalamine/server.py
kalamine/template.py
kalamine/tpl/base.xkb_keymap
kalamine/tpl/base.xkb_symbols
kalamine/tpl/full.xkb_keymap
kalamine/tpl/full.xkb_symbols
kalamine/tpl/full_1dk.xkb_keymap
kalamine/tpl/full_1dk.xkb_symbols
kalamine/xkb_manager.py
tests/test_serializer_xkb.py

fixes #97 and outputs less ambiguous xkb files (hopefully):
- the `.xkb_keymap` file (formerly `*.xkb`) is a full, standalone file, to be used with `xkbcomp`
- the `.xkb_symbols` file (formerly `*.xkb_custom`) is meant to be put in `xkb/symbols/custom` 
Both files now have a header that should give clear explanations on their purpose.

[xkb] `*.xkb_keymap` and `*.kkb_symbols` outputs

---

.github/workflows/tests.yml
Makefile
kalamine/msklc_manager.py

Catch errors on generating DLLs instead of panicking.
Restore write permission on C files on error to avoid permission denied error on next run
Revert back to `\n` line separator because I don’t know why, but on my system, `\r\n` ends into `\r` only in the file and rejected by `kbdutools`

fix: more error checking

---

kalamine/layout.py
kalamine/msklc_manager.py
kalamine/template.py
pyproject.toml

I added a section in pyproject to disable mypy on third party lib `progress`

feat: scan registry for installed driver, progress bar

---

kalamine/template.py
tests/test_macos.py
tests/test_serializer_keylayout.py
tests/util.py

[keylayout] bugfix: unique action IDs

---

kalamine/generators/klc.py
kalamine/layout.py

Fixes https://github.com/OneDeadKey/kalamine/issues/172

fix: angle mod failure

---

docs/README.md
kalamine/data/user_guide.yaml

Provides documentation to resolve https://github.com/OneDeadKey/kalamine/issues/176

docs: fix wrong dead acute accent

---

kalamine/layout.py

Closes #144 by adding the required number of ".0" to match x.y.z format. instead of exiting, kalamine now replaces the version number such as:
1 → 1.0.0
1.2 → 1.2.0
if no version is provided, default value will be used

Feat: Builds even if version number is too short (i.e. not x.y.z format)

---

Makefile
pyproject.toml
uv.lock

`uv` makes it so much easier to handle dependencies and `venv`. Amazing stuff.
@gagath any idea of what should be done to make it suitable for you as a Debian maintainer?

uv + uv.lock
